learning_users/basic_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls import urls
from .views import *


app_name = 'basic_app'

urlpatterns = [
    # path('index/',index,name='index'),
    path('register/',register,name='register'),
    path('user_logout/',user_logout,name='user_logout'),
    path('userlogin/',userlogin,name='userlogin'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import urls
from basic_app import views

urlpatterns = [
    path('index/',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('',include(urls)), #basic_app
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
# """A model to store user information."""
    user = models.OneToOneField(User,on_delete=models.CASCADE)
# OneToOneField is a type of
    id_number = models.CharField(max_length=20, blank=True)
    position = models.CharField(max_length=100, blank=True)
    company = models.CharField(max_length=100, blank=True)
    portfolio_site = models.URLField(blank=True)
    phone = models.CharField(max_length=20, blank=True)
    Email_address =models.CharField(max_length=100, blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic',blank=True)



    def __str__(self):
        return self.user.username
    

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ['username','password']

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        # include = ['porfolio_site','profile_pic','id_number','position','compeny']
        include = ['profile_pic','id_number','position','compeny','Email_address','phone']
        exclude = ['user']

learning_users/basic_app/views.py
from django.shortcuts import render,redirect,HttpResponse,HttpResponseRedirect
from .forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from . import views
from .models import UserProfileInfo




# Create your views here.



def index(request):
    user = request.user  # Get the authenticated user
    return render(request, 'index.html', {'user': user})



def register(request):

    registered = False

    if request.method =='POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if  user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()


            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        
        else:

            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'registration.html',
                  {'user_form':user_form,'profile_form':profile_form,'registered':registered})




'''
View --> Login  View Function
'''

def userlogin(request):

    if request.method == 'POST':
        username_1 = request.POST.get('username')
        pwd = request.POST.get('password')
        user = authenticate(username=username_1,password=pwd)

        if user:
            if user.is_active:
                login(request,user)
                Userinfo=UserProfileInfo.objects.get(user=user)
                print(Userinfo)
                context={"userinfo":Userinfo}
                return render(request,"index.html",context)
            
            else:
                return HttpResponse('User Not Active')
        
        else:
            print('Login Failed due to Wrong User Login')
            return HttpResponse("Invalid Login Details")
        
    else:
        return render(request,'login.html')



''' 
Logout User
'''
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

learning_users/basic_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

     <link rel="stylesheet" href="{% static 'assests/css/style.css' %}" />
     
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   



    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">Dashboard</a>
          
          
            <ul class="navbar-nav">
              <li><a class="navbar-link list" href="{% url 'admin:index' %}">Admin</a></li>
              <li><a class="navbar-link list" href="{% url 'basic_app:register' %}">Register</a></li> 
              {% if user.is_authenticated %}
              <li><a class="navbar-link list" href="{% url 'basic_app:user_logout' %}">Logout</a></li>
              {% else %}
              <li><a class="navbar-link" href="{% url 'basic_app:userlogin' %}">Login</a></li>
              {% endif %}
            </ul>
           
          </div>
        </div>
      </nav>
      
    {% block body_block %}

    {% endblock %}

</body>
</html>

<style>
    a {
  color: rgba(var(--bs-link-color-rgb), var(--bs-link-opacity, 1));
  text-decoration: underline;
  margin-left: 24px;
  text-decoration: none;
}
img.pics {
    width: 125%;
    background-color: aquamarine;
    margin-left: 375px;
    
}
.banner{
  width: 1263px;
  height: 200px;
}
h1.person{
color: red;
text-align: center;
}
p.details {
    color: green;
    font-size: x-large;
}
h1.register {
    text-align: center;
    color: green;
    font-size: xx-large;
}
.wrapper.login {
    text-align: center;
}
.passw {
    margin-top: 13px;
    margin-left: 8px;
}
button.log {
    margin-top: 13px;
    margin-left: 40px;
    color: green;
}
h.hear {
    font-size: xx-large;
    font-style: italic;
    color: tomato;
    margin-left: 40px;
}
span#id_username_helptext {
    display: none;
}
.wrapper.register_form {
    text-align: center;
    background-color: wheat;
    width:50%
}
input#id_position {
    margin-left: 10px;
}
input#id_phone {
    margin-left: 16px;
}
</style>

learning_users/basic_app/templates/index.html
{% extends 'base.html' %}

{% block body_block %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
</head>

<body>
    <div>
        <img src="{% static 'assests/images/benner_5.jpg' %}" alt="Background Image" class="banner">

    </div>
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="person">{{ user.username }}</h1>
            </div>
        </div>
    </div>
</section>
    <section>
        <div class="container id">
            <div class="row">
                <div class="col-md-6">
                    {% if userinfo.profile_pic %}
                    <!-- <img src="{{userinfo.profile_pic.url}}" class="pics" alt="Profile Picture"> -->
                    <img src="{{ userinfo.profile_pic.url }}" class="pics" alt="Profile Picture"
                        style="width: 150px; height: 160px; border-radius: 50%; box-shadow: 2px 2px 5px rgba(0,0,0,0.3);">

                    {% endif %}
                </div>
                <div class="col-md-6">
                    <p class="details"> {{ userinfo.id }}</p>
                    <p class="details"> {{ userinfo.position }}</p>
                    <p class="details"> {{ userinfo.company }}</p>
                    <p class="details"> {{ userinfo.phone }}</p>
                    <p class="details"> {{ userinfo.Email_address }}</p>
                </div>
                

            </div>
        </div>
    </section>
    

    

    <!-- You can display other user details here -->
</body>

</html>





{% endblock %}

learning_users/basic_app/templates/login.html
{% extends 'base.html' %}
{%load static%}
{% block body_block %}

<div class="wrapper login">
    <h class="hear">Login hear</h>
    <form action="{% url 'basic_app:userlogin' %}" method="post">
        {% csrf_token %}
        <div class="usern">
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">
    </div>
    <div class="passw">
        <label for="password">Password:</label>
        <input type="password" name="password" placeholder="Enter Password">
    </div>
        <button type="submit" class="log">Login</button>
    </form>
</div>
{% endblock %}

learning_users/basic_app/templates/registration.html
{% extends 'base.html' %}

{% load static %}

{% block body_block %}
<section>
    <div class="cotainer">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="wrapper register_form">
                {% if registered %}
                <h1>Registered Successfully!
                    {% else %}
                    <h1 class="register">Register Here</h1>
                    <!-- <h2 class="fill">Fill Out The Form:</h2> -->
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{user_form.as_p}}
                        {{profile_form.as_p}}
                        <input type="submit" name="" value="Register">
                    </form>
                    {% endif %}
            </div>
        </div>
        </div>
    </div>
</section>

{% endblock %}